name: Test within environments
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
on: [push, pull_request]
jobs:
  test-uv:
    runs-on: ${{ matrix.os }}
    name: uv tests (${{ matrix.os }}, py${{ matrix.python }})
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        python: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: uv sync --all-extras
      - name: Run pure tests
        run: uv run --extra test pytest -m pure
      - name: Run interpolation tests
        run: uv run --extra test --extra interpolation pytest -m interpolation
      - name: Run align tests
        run: uv run --extra test --extra analysis pytest -m align
  test-pixi:
    runs-on: ${{ matrix.os }}
    name: pixi tests (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.10
        with:
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
          activate-environment: false
      - name: Run fragments tests
        shell: bash -el {0}
        run: |
          pixi r -e fragments pytest -m fragments
      - name: Run surfaces tests
        shell: bash -el {0}
        run: |
          pixi r -e surfaces pytest -m surfaces
